### ISSUE TITLE
rewrite docs suggestion

### ISSUE THREAD

**Issue by jacobdalamb** [nushell/nushell.github.io#1231] opened 2024-01-29 15:40 UTC
I think a docs rewrite using [starlight](https://starlight.astro.build/) would be great enhancement for the site. It could benefit from better [performance and accessibility](https://pagespeed.web.dev/analysis/https-www-nushell-sh/jd1z8mksy4?form_factor=mobile), improved SEO, can maintain the existing design with a more streamlined look and has a excellent developer experience.

**Comment by fdncred** [comment] 2024-01-29 15:44
we're always interested in making things better but it's not clear how that is true with starlight.

**Comment by jacobdalamb** [comment] 2024-01-29 15:57
> starlight

I can I think of a few improvements on top of the ones I mentioned. Starlight comes with copy and paste buttons for code blocks, "gives you built-in frontmatter validation with TypeScript type-safety", built-in components, and in my opinion custom block containers (tip, caution, and note) that are visually styled better.

**Comment by fdncred** [comment] 2024-01-29 15:59
And does it support styling/highlighting nushell language syntax?

**Comment by jacobdalamb** [comment] 2024-01-29 16:13
> And does it support styling/highlighting nushell language syntax?

Yes. https://github.com/shikijs/textmate-grammars-themes/blob/main/packages/tm-grammars/README.md

**Comment by fdncred** [comment] 2024-01-29 16:21
It would be nice to have something that supports tree-sitter-nu too at some point. That grammar is coming along nicely.

**Comment by hustcer** [comment] 2024-01-30 00:22
There are tons of SSG tools, and I don't think it has great advantage over Rspress, especially talking about building performance and Rspress add shiki plugin support recently.
Related: https://github.com/nushell/nushell.github.io/issues/1126

**Comment by jacobdalamb** [comment] 2024-01-30 03:47
> There are tons of SSG tools, and I don't think they have great advantage over [Rspress](https://rspress.dev/), especially talking about building performance. BTW: Rspress adds shiki plugin support recently. Glad if you prove me wrong. Related: #1126

Another great alternative to the current docs. Both are good.

**Comment by jacobdalamb** [comment] 2024-02-07 18:56
> It would be nice to have something that supports tree-sitter-nu too at some point. That grammar is coming along nicely.

Would you be interested in a PR to see what the site would look like using Starlight?

**Comment by fdncred** [comment] 2024-02-07 20:00
I personally wouldn't mind seeing a PR but it would have to:
1. be as easy or easier to manage than what we have now
2. look as good or better than what we have now
3. translations would need to work as good or better than what we have now
4. @hustcer would need to approve of it since he manages a lot of the site for us now (we'd have to have other core-team members approve too in order to move to it, but not really needed for a preview)
5. we'd also need a way to preview it somehow

**Comment by hustcer** [comment] 2024-02-07 21:26
@jacobdalamb 

There are two things I most care about:
1. Build speed, we have lots of docs now, the build speed is not fast enough, in the future we also intend to support multiple versions and the build speed requirements are higher.We do not support multiple versions also due to the slow build speed.
2. The new approach need to support multiple versions, which is especially important after version v1.0.
You can try to solve these two points with Starlight.

**Comment by NotTheDr01ds** [comment] 2024-08-07 21:32
I'd like to consider closing this as a duplicate of #1126 and continuing the discussion there.  If agreed, go ahead and close it.  I'll then copy over a summary of new information in this issue so it can be consolidated in one place.

**Comment by fdncred** [comment] 2024-08-07 21:59
ya, seems like a dupe to me. thx.

**Closed by fdncred** 2024-08-07 21:59 UTC
