### ISSUE TITLE
Why I can not run `R.exe` in nushell?

### ISSUE THREAD

**Issue by danli349** [nushell/nushell.github.io#1156] opened 2023-11-26 00:42 UTC
Hello

Why I can not run `R.exe` in nushell?
```
~/R/R-4.3.1/bin> ./R.exe                                                                        1 11/25/2023 07:38:33 PMThe system cannot find the path specified.
~/R/R-4.3.1/bin> R.exe                                                                          1 11/25/2023 07:38:44 PM
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #12:1:1]
 1 │ R.exe
   · ──┬──
   ·   ╰── executable was not found
   ╰────
  help: program not found
```

when I try
```
~/R/R-4.3.1/bin> R
```
R started correctly. 

Thanks

**Comment by fdncred** [comment] 2023-11-27 14:50
I can't reproduce on Windows.
![image](https://github.com/nushell/nushell.github.io/assets/343840/745f2f8c-88f8-4b91-a146-04e3a7247000)

**Comment by sholderbach** [comment] 2024-02-14 14:57
Closing this one as we need more information to figure out why it is going wrong (and this repo tracks only the documentation)

Please feel free to [open an issue on the main repo](https://github.com/nushell/nushell/issues/new/choose) where we have some steps to guide you on which information to provide so we can figure out system specific problems.

**Closed by sholderbach** 2024-02-14 14:57 UTC
