### ISSUE TITLE
Better tables in examples

### ISSUE THREAD

**Issue by sophiajt** [nushell/nushell.github.io#11] opened 2019-11-27 18:49 UTC
I noticed some people talking about how tables looked in different browsers on Reddit, and then when I checked nushell.sh I noticed a similar thing.  Here's what I see in Firefox+Windows:

![image](https://user-images.githubusercontent.com/547158/69751233-8b2cab00-11b3-11ea-8741-49e46030525a.png)

I wonder if there's a way to either render this the same across browsers, or if maybe we should just put an image there instead.

**Comment by jonathandturner** [comment] 2019-11-27 18:50
Even fancier: like the scripts we use to create the examples, maybe there's a way to script creating those images (if we end up using images)

**Comment by Aloso** [comment] 2019-11-27 19:16
I guess a monospaced webfont which includes the box-drawing characters would work.

**Comment by Aloso** [comment] 2019-11-27 23:21
My favourite monospace fonts are [Source Code Pro](https://fonts.google.com/specimen/Source+Code+Pro) and [Fira Code](https://fonts.google.com/specimen/Fira+Code).

Source Code Pro:

![Source](https://user-images.githubusercontent.com/15658558/69765538-9ad8cf00-1174-11ea-9971-6a5969a3e8d5.png)

Fira Code:

![Fira](https://user-images.githubusercontent.com/15658558/69765539-9d3b2900-1174-11ea-857f-5e7852bd0048.png)

Source Code Pro:

![Source2](https://user-images.githubusercontent.com/15658558/69765546-a1ffdd00-1174-11ea-9b9d-2d11b8c0b539.png)

Fira Code:

![Fira2](https://user-images.githubusercontent.com/15658558/69765549-a5936400-1174-11ea-8fae-9a597f336405.png)

I'd be happy to make a PR to include a font :)

**Comment by jonathandturner** [comment] 2019-11-28 00:17
@Aloso - if you include the font, does it work across browsers/platforms? 

I assume so, but figured I'd ask just to be sure

**Comment by jonathandturner** [comment] 2019-11-28 00:17
I do like that Fira Code one, too :)

**Comment by Aloso** [comment] 2019-11-28 00:52
The line is only that way because I zoomed before taking the screenshot :D

**Comment by jonathandturner** [comment] 2019-11-28 06:09
@Aloso sounds good

**Comment by Aloso** [comment] 2019-11-28 17:12
@jonathandturner I tried this on my phone. To my surprise using one of these fonts doesn't fix the issue. It might be related to the OS' font stack.

Anyway, I found a workaround, which, unfortunately involves some JS and generates a `<u>` element for each horizontal line character (`━`, `─`).

**Comment by jonathandturner** [comment] 2020-01-09 17:36
As @sebastian-xyz points out, our recent fix to get the font rendering issue (dark-on-dark rendering) fixed, we had to unfix this issue.

We should explore a better solution here.

**Comment by jonathandturner** [comment] 2020-01-09 18:00
@sebastian-xyz - one thing we could do is instead of relying on the monospaced font, we could draw the tables either using markdown tables (or maybe html tables?) or rendering them to images and using those

**Comment by jonathandturner** [comment] 2020-01-09 18:13
Also strange (but hopeful): the github renderer for markdown looks fine in Firefox on Windows, if we don't us the `shell` mode for code snippets:

![image](https://user-images.githubusercontent.com/547158/72093071-952bf700-3378-11ea-89c4-17ec1c4ca0d0.png)

Maybe we can switch to using what they're using?

**Comment by jonathandturner** [comment] 2020-01-09 19:07
Seems like the easiest fix is just to move the table drawing to use the same top and bottom line as the interior line. 

The bold line was very subtle to begin with, and I don't think it's really worth keeping if it causes rendering issues across platforms.

**Comment by sebastian-xyz** [comment] 2020-01-09 19:23
I started some research on the different markdown processors on the [jekyll website](https://jekyllrb.com/docs/configuration/markdown/) and played around with some of the processors. But I didn't have much success until now. 

> 
> 
> Seems like the easiest fix is just to move the table drawing to use the same top and bottom line as the interior line.
> 
> The bold line was very subtle to begin with, and I don't think it's really worth keeping if it causes rendering issues across platforms.

This is how the table looks like with the thin lines
![thin_lines](https://user-images.githubusercontent.com/52786998/72097525-dc849a00-331c-11ea-971a-30476851b004.png)

The readbiltity is definitely better.
Seems like a good quick fix. We definitely need to find a better way to draw the tables.

**Comment by jonathandturner** [comment] 2020-01-09 19:31
Yeah, let's just convert to thin lines, then.  I've updated a few of the pages just to be sure it will work.

I'll also add a PR to update the actual table drawing to use thin lines too. I figure, we might as well :)

**Comment by homburg** [comment] 2020-01-09 20:05
Thin lines still needs some css to render width "monospace width" in chrome on macOS. You can use the default macOS terminal font, with fallback to monospace:

`font-family: monospace;`
<img width="833" alt="Screenshot 2020-01-09 at 20 38 46" src="https://user-images.githubusercontent.com/235886/72100655-5029a580-3323-11ea-8927-0e51ef0cfb74.png">

`font-family: Menlo, monospace;`
<img width="841" alt="Screenshot 2020-01-09 at 20 40 37" src="https://user-images.githubusercontent.com/235886/72100690-5c156780-3323-11ea-8b8d-1805f9978307.png">

**Comment by sebastian-xyz** [comment] 2020-01-09 20:13
@homburg - Does this font work across platforms and browsers?

**Comment by homburg** [comment] 2020-01-09 20:17
I think Menlo is only installed by default on macOS, but other platforms will fall back to the "monospace" definition.

**Comment by jonathandturner** [comment] 2020-01-09 20:34
@homburg - our previous fix was something like this, where it should fallback between fonts. Unfortunately, we had to remove the fix because it rendered dark text on dark backgrounds for some versions of Firefox.

**Comment by Aloso** [comment] 2020-01-09 20:40
Which versions are you referring to?

I'm sure this can be fixed, either by adjusting some CSS or by using `font-feature-settings`.

**Comment by sebastian-xyz** [comment] 2020-01-09 20:40
I tested this with `font-family: Menlo,Consolas,monospace` on windows since Consolas is the default terminal font there. This looked pretty good.

I think the fall back might work this time because the fonts don't need to be added to the source of the website because they are part of the system.

**Comment by sebastian-xyz** [comment] 2020-01-09 20:45
This was the example in the discord discussion a few days back:

<img width="938" alt="unknown" src="https://user-images.githubusercontent.com/52786998/72103302-37bc8980-3329-11ea-8b13-398323eb7480.png">

**Comment by Aloso** [comment] 2020-01-09 21:32
I found the discussion on Discord. Here's what I don't understand:

- the web font (which fixes this issue) was disabled to fix another bug
- that bug is neither confirmed, nor can be reproduced
- we don't know what caused that bug
- we don't know if disabling the web font fixed that bug
- we don't know anything about that bug, except that it appeared in Firefox.

@jonathandturner @sebastian-xyz  I vote to enable the web font again, until we know more.

**Comment by Aloso** [comment] 2020-01-09 22:19
If a web font is not an option, we need to list monospaced fonts that are available on common operating systems and support box drawing characters. This could work:

```css
font-family: Consolas, Menlo, Monaco, Hack, Roboto Mono, Droid Sans Mono, Liberation Mono, monospace;
```

**Comment by jonathandturner** [comment] 2020-01-09 23:19
Let's give it a try and see if it fixes the issue for people

**Comment by caio** [comment] 2021-08-06 13:17
Hi,

https://github.com/nushell/nushell.github.io/blob/668f69319021745c6ebf28c5b8e2a82485ed8ce2/.vuepress/theme/layouts/Layout.vue#L20

Shouldn't there be at least a `'monospace'` entry here so that the browser can fall back to whatever is the default monospace font the user configured?

My browser doesn't load remote fonts and I don't have any of the listed fonts installed, so it picks up a serif font and the tables at https://www.nushell.sh/book/ end up looking more like spaghetti.

**Comment by NotTheDr01ds** [comment] 2024-08-07 19:33
Checking to see if this can be closed - `monospace` was added over 4 years ago, the issue was closed, then reopened -- Has anyone reported related issues in the intervening 4 years?

**Comment by fdncred** [comment] 2024-08-07 19:42
i think we can close this now. thanks for finding it.

**Closed by fdncred** 2024-08-07 19:42 UTC

**Comment by Aloso** [comment] 2024-08-09 22:27
@fdncred the issue was reopened because it wasn't fixed (actually, I fixed it, but the fix was reverted without explanation).

Check, for example: https://www.nushell.sh/book/quick_tour.html on **Chrome for Android** or **Firefox for Android**. The issue is still present.

**Comment by fdncred** [comment] 2024-08-09 22:29
@Aloso can you point to the PR where it was fixed and reverted?

**Comment by NotTheDr01ds** [comment] 2024-08-10 00:16
@Aloso The Android issue is #83 and is still open, and yes, I confirmed that it is still an issue. However, this issue was about other platforms, including Windows, and it has been resolved AFAICT.
